"use client";

import { use } from "react";
import { useQuery } from "@tanstack/react-query";
import { ContextLink, PageHeader, StatusLozenge } from "../../../components/atlas";
import type { JobResult } from "../../../domain/types";

interface JobView { key: string; queue: string; state: string; errorCode?: string; createdAt: string; updatedAt: string; result?: JobResult; latest?: { phase: string; state: string }; events: Array<{ sequence: number; phase: string; state: string; detail: Record<string, unknown>; createdAt: string }> }

export default function JobPage({ params }: { params: Promise<{ jobId: string }> }) {
  const { jobId } = use(params);
  const query = useQuery<JobView>({ queryKey: ["job", jobId], queryFn: async () => { const response = await fetch(`/api/jobs/${jobId}`); if (!response.ok) throw new Error("JOB_UNAVAILABLE"); return response.json(); }, refetchInterval: ({ state }) => ["COMPLETE", "FAILED", "CANCELLED"].includes(state.data?.state ?? "") ? false : 1_000 });
  const latest = query.data?.events.at(-1);
  const result = query.data?.result;
  const nextHref = result && "nextHref" in result ? result.nextHref : undefined;
  return <div className="stack-lg"><PageHeader eyebrow="Ingest · durable job evidence" title={`Job ${jobId}`} description="Each phase is persisted and polled from the runtime. Partial and failed states remain explicit." action={<StatusLozenge state={query.data?.state ?? "LOADING"} />} />{query.error && <section className="panel danger" role="alert"><h2>Job status unavailable</h2><p>Polling failed before a durable response was read.</p><button className="button" onClick={() => void query.refetch()}>Retry job query</button></section>}{query.data && <section className="evidence-tray"><div className="grid-3"><div><span className="eyebrow">Job type</span><strong>{query.data.queue}</strong></div><div><span className="eyebrow">Job key</span><code className="hash">{query.data.key}</code></div><div><span className="eyebrow">Active phase</span><strong>{latest?.phase ?? "QUEUED"}</strong></div></div><p className="mono muted">Created {query.data.createdAt} · updated {query.data.updatedAt}</p></section>}{query.data?.errorCode && <p role="alert" className="danger">{query.data.errorCode}</p>}<ol className="stack">{query.data?.events.map((event, index, events) => { const previous = events[index - 1]; const duration = previous ? Date.parse(event.createdAt) - Date.parse(previous.createdAt) : undefined; return <li className="evidence-tray" key={event.sequence}><div className="row" style={{ justifyContent: "space-between" }}><strong>{event.phase}</strong><StatusLozenge state={event.state} /></div><p className="mono muted">{event.createdAt}{duration !== undefined && Number.isFinite(duration) ? ` · +${duration}ms from prior event` : ""}</p><details><summary>Raw event detail</summary><pre>{JSON.stringify(event.detail, null, 2)}</pre></details></li>; })}</ol>{query.data && !query.data.events.length && <p className="panel muted">Waiting for the first durable event.</p>}{query.data?.state === "COMPLETE" && result && <section className="panel"><h2>Workflow next action</h2><p className="muted">Result <span className="mono">{result.kind}</span> is durably attached to this job.</p>{nextHref ? <ContextLink className="button primary" href={nextHref}>Continue workflow</ContextLink> : <p className="muted">No onward page is defined for cleanup jobs.</p>}</section>}{query.data?.state === "COMPLETE" && !result && <section className="panel"><h2>Result unavailable</h2><p role="alert">The job completed without a typed result. No destination was inferred.</p></section>}{latest && ["FAILED", "CANCELLED"].includes(latest.state) && <section className="panel danger"><h2>Workflow stopped</h2><p>Inspect the durable event, correct the refused input, then retry from the originating route.</p></section>}</div>;
}
