import { listPortfolioSnapshots } from "../../db/repository";
import { ContextLink, EmptyState, MetricTile, PageHeader, StatusLozenge } from "../../components/atlas";

export const dynamic = "force-dynamic";

export default async function PortfolioPage({ searchParams }: { searchParams: Promise<{ portfolio?: string }> }) {
  const portfolioKey = (await searchParams).portfolio ?? "default";
  const rows = await listPortfolioSnapshots(portfolioKey);
  const packages = rows.reduce((sum, row) => sum + row.packageCount, 0);
  const edges = rows.reduce((sum, row) => sum + row.edgeCount, 0);
  return <div className="stack-lg"><PageHeader eyebrow="Investigate · immutable application portfolio" title="Portfolio" description={`Scope ${portfolioKey}. Exact repository snapshots are the only inputs to graph proof.`} /><div className="grid-4"><MetricTile tone="accented" value={rows.length} label="application snapshots" /><MetricTile value={packages} label="package instances" /><MetricTile value={edges} label="typed dependency edges" /><MetricTile value={rows.length ? Math.max(...rows.map((row) => row.maxDepth)) : 0} label="maximum depth" /></div><div className="stack">{rows.map((row) => <article className="panel portfolio-row" key={row.key}><div className="row" style={{ justifyContent: "space-between" }}><h2>{row.repository}</h2><StatusLozenge state="IMMUTABLE" /></div><p className="mono">{row.commitSha}</p><code className="hash">{row.lockfileSha256}</code><p>{row.packageCount} package instances · {row.edgeCount} typed edges · depth {row.maxDepth}</p><div className="density-track" aria-label={`${row.edgeCount} edges across ${row.packageCount} packages`}><span style={{ width: `${Math.min(100, row.packageCount ? (row.edgeCount / row.packageCount) * 12 : 0)}%` }} /></div><p className="muted">Snapshot freshness: persisted at source retrieval time.</p><ContextLink className="button" href={`/incidents?application=${encodeURIComponent(row.repository)}&portfolio=${encodeURIComponent(portfolioKey)}`}>Investigate application</ContextLink></article>)}</div>{!rows.length && <EmptyState title="No immutable snapshots in this scope" description="Import an exact public ref or local manifest and lockfile before portfolio evidence can be displayed." action={<ContextLink className="button" href={`/imports?portfolio=${encodeURIComponent(portfolioKey)}`}>Import portfolio evidence</ContextLink>} />}</div>;
}
