import { ContextLink } from "../../components/command-surface";
import { listReceipts } from "../../db/repository";
import { CopyButton, EmptyState, MetricTile, PageHeader, StatusLozenge } from "../../components/atlas";

export const dynamic = "force-dynamic";

export default async function ProofIndexPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const rows = await listReceipts();
  const params = searchParams ? await searchParams : {};
  const state = typeof params.state === "string" ? params.state : "verified";
  const after = typeof params.after === "string" ? params.after : "";
  const filtered = rows.filter((row) => (state === "all" || row.resultState.toLowerCase().includes(state)) && (!after || row.createdAt >= new Date(`${after}T00:00:00.000Z`)));
  return <div className="stack-lg"><PageHeader eyebrow="Prove · immutable evidence" title="Proof receipts" description="Receipts are discoverable only after fresh native traversal and every refusal gate passes." /><div className="grid-4"><MetricTile tone="accented" value={filtered.length} label="immutable receipts" /><MetricTile value={filtered.filter((row) => row.resultState.includes("VERIFIED")).length} label="verified within bounds" /><MetricTile value={filtered.reduce((sum, row) => sum + row.receipt.final.pairs.length, 0)} label="bounded final pairs" /><MetricTile value="SHA-256" label="canonical digest" /></div><form className="evidence-tray filter-bar" method="get"><label>Result state<select name="state" defaultValue={state}><option value="verified">Verified within bounds</option><option value="all">All persisted states</option></select></label><label>Created after<input name="after" type="date" aria-label="Created after" defaultValue={after} /></label><button className="button" type="submit">Apply filters</button><span className="mono muted">{filtered.length} receipts · newest first</span></form>{filtered.length ? <div className="stack">{filtered.map((row) => <article className="panel receipt-row" key={row.digest}><div className="row" style={{ justifyContent: "space-between" }}><div><p className="eyebrow">{row.receipt.incidentKey}</p><h2>{row.resultState}</h2></div><StatusLozenge state={row.resultState} /></div><p className="mono hash">{row.digest}</p><p className="muted">Created {row.createdAt.toISOString()} · {row.receipt.baseline.pairs.length} baseline → {row.receipt.final.pairs.length} final pairs</p><div className="row"><CopyButton value={row.digest} /><ContextLink className="button" href={`/proof/${row.digest}`}>Open immutable receipt</ContextLink></div></article>)}</div> : <EmptyState title="No receipt matches this evidence view" description="Adjust the filters or complete a fresh combined native traversal. No receipt appears before every refusal gate passes." action={<ContextLink className="button" href="/incidents">Open incident command</ContextLink>} />}</div>;
}
