import { databaseHealth } from "../../db/client";
import { loadSystemFacts } from "../../db/repository";
import { hydraHealth } from "../../integrations/hydradb";
import { CopyButton, MetricTile, PageHeader, StatusLozenge } from "../../components/atlas";

export const dynamic = "force-dynamic";

export default async function SystemPage() {
  const [database, hydradb, facts] = await Promise.all([databaseHealth(), hydraHealth(), loadSystemFacts()]);
  return <div className="stack-lg"><PageHeader eyebrow="Operate · runtime evidence" title="System" description="The operator boundary stays visible: web and worker are public surfaces; PostgreSQL and HydraDB remain private." /><section className="grid-4"><MetricTile tone="accented" value={database ? "READY" : "DOWN"} label="PostgreSQL" /><MetricTile value={hydradb ? "READY" : "DOWN"} label="HydraDB OSS" /><MetricTile value="NATIVE" label="OpenCypher + algo.MSpaths" /><MetricTile value="PRIVATE" label="graph network boundary" /></section><section className="grid-2"><article className="evidence-tray"><div className="row"><h2>Service topology</h2><StatusLozenge state={database && hydradb ? "VERIFIED_WITHIN_BOUNDS" : "PARTIAL"} /></div><svg className="service-topology" viewBox="0 0 760 180" role="img" aria-label="Web and worker connect to PostgreSQL and private HydraDB"><path d="M130 90h70m110 0h70m110 0h70" className="topology-line"/><rect x="30" y="63" width="100" height="54"/><rect x="200" y="63" width="110" height="54"/><rect x="380" y="63" width="110" height="54"/><rect x="560" y="63" width="150" height="54"/><text x="80" y="95">web</text><text x="255" y="95">worker</text><text x="435" y="95">PostgreSQL</text><text x="635" y="95">HydraDB OSS</text><text x="635" y="40">private graph network</text></svg><p className="muted">HydraDB remains on the private graph network; no source code or secrets are exposed here.</p></article><article className="evidence-tray"><h2>Graph image digest</h2><div className="row"><code className="hash">{facts.graphImageDigest}</code><CopyButton value={facts.graphImageDigest} /></div><p className="muted">Digest-pinned runtime image.</p></article></section><details className="panel"><summary>Raw runtime facts</summary><div className="row"><CopyButton value={JSON.stringify(facts)} /></div><pre>{JSON.stringify(facts, null, 2)}</pre></details></div>;
}
